route:
    receiver: 'slack'
 
receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            username: 'Alert-Manager'
            channel: '#alerts'
            title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
            text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
            api_url: 'https://hooks.slack.com/services/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'