version: '3.7'
volumes:
  grafana-storage:
  prometheus:
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
      - prometheus:/prometheus
    ports:
      - 9090:9090
    networks:
      - "monitoring-network"
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000  
    networks:
      - "monitoring-network"
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    networks:
      - "monitoring-network"
  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
networks:
  monitoring-network:
    driver: bridge